name: "Build Debian Live Nano ISO"

on:
  schedule:
  # 7AM on the 1st of every month (GitHub is GMT)
  # https://crontab.guru/#0_7_1_*_*
    - cron: "0 7 1 * *"

  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "ISOSTAMP=$(date +'%Y%m')" >> $GITHUB_ENV 

      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./build.sh

      - name: "Publish Date-Time"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.DATESTAMP }}"
          title: "Debian Stable Live Nano ISO"
          files: |
            output/debian-stable-live-nano-x86_64-${{ env.ISOSTAMP }}.iso
            output/packages.txt

      - name: "Delete latest"
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: 'latest'
          suppress_errors: true

      - name: "Publish"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Debian Stable Live Nano ISO"
          files: |
            output/debian-stable-live-nano-x86_64-latest.iso
            output/packages.txt
